### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by cahyod** [OWASP/www-project-top-10-insider-threats#12]
https://owasp.org/www-project-top-10-infrastructure-security-risks/docs/2024/INT_2024-Open_Call_for_Data
<img width="649" alt="broken-link" src="https://github.com/user-attachments/assets/48c21c4b-60f2-4386-b606-d2104f2ee3be">

**Comment by Sharkeonix** [comment]
Thanks @cahyod. Pull request for fix created.
